### ISSUE TITLE
breakdown when find no face

### ISSUE THREAD

**Issue by a00achild1** [ffmmjj/kairos-face-sdk-python#2]
Hi, I wrote a program to automatically enroll and verify
But when the API could not find face in the given image, it broke down
Is there any way to make it continue even if the program has some exception?

> Traceback (most recent call last):
  File "run_ROC_test.py", line 75, in <module>
    args.start_threshold, args.end_threshold, args.threshold_step)
  File "run_ROC_test.py", line 51, in main
    kairos_face.enroll_face(subject_index, 'ROC', file=image_path)
  File "/usr/local/lib/python2.7/dist-packages/kairos_face/enroll.py", line 26, in enroll_face
    raise exceptions.ServiceRequestError(response.status_code, json_response, payload)
kairos_face.exceptions.ServiceRequestError: {u'Errors': [{u'Message': u'no faces found in the image', u'ErrCode': 5002}]}

**Comment by a00achild1** [comment]
I solve this by commenting the `raise exceptions.ServiceRequestError` in the file, and reinstall with pip

**Comment by ffmmjj** [comment]
Hi, and sorry for taking this long to answer.
This exception is simply passing the response obtained from the Kairos service itself. One thing that you can do is to catch the ServiceRequestError exception and handle it according to the `ErrCode` passed in the exception contents, instead of changing the library itself.

Since not having a face in the image is not exactly an unexpected situation, it may be worth handling this scenario in the library itself and make it return something less intrusive, but I'll need some more time to think about it.

**Comment by a00achild1** [comment]
@ffmmjj thank you for your reply, I will try to handle the exception outside the library.
