### ISSUE TITLE
invalid url error when using address with port (www.some.domaing:port)

### ISSUE THREAD

**Issue by adnan6336** [ffmmjj/kairos-face-sdk-python#5]
Hi there, 
I got invalid url error when using http://192.168.15.34:8080/shot.jpg but works fine when using any other url i-e without port address.
although I have checked this address (http://192.168.15.34:8080/shot.jpg) through ulrlib and its working fine there :(

**Comment by ffmmjj** [comment]
Hi,
The IP address that you used as example is a private IPv4 address, so it won't be accessible by Kairos' service. Does this error also happen when you use a publicly-available URL to the image?

**Comment by adnan6336** [comment]
No, when i use other ips such as www.anydomain.com/any.jpg, it works fine
but I need to use private ip, for now I have used urllib to retrive image
from private ip then use local file method to enroll on kairos and its
working.

**Comment by adnan6336** [comment]
But I am a bit confused that urllib can access my private ip and download
joh from there but kairos does'nt, why?

**Comment by ffmmjj** [comment]
The URL needs to be publicly accessible so that Kairos's service can retrieve the image for analysis:  the `enroll_face` function doesn't download the image and passes its contents to Kairos, it simply performs a POST request to the `enroll` endpoint passing the URL itself as described in [this link](https://www.kairos.com/docs/api/#post-enroll).

The library could pull the image and pass its base64-encoded contents to the endpoint, but that would diverge a lot from the model used by Kairos' Face Recognition API - so I don't think it would be a good idea to implement this in the library itself (better to let the client application decide if the URL or the image contents should be passed to the service by using the appropriate function calls).

**Comment by ffmmjj** [comment]
```
But I am a bit confused that urllib can access my private ip and download
joh from there but kairos does'nt, why?
```
That's probably because you're running `urllib` within a client that's in the same network as the IP address that you provided. This IP address is only visible inside your network, so Kairos' servers are unable to resolve it.

**Comment by adnan6336** [comment]
Wow, I totally understand now.
Actually I am doing realtime face recognition via ip camera, and doing post
request once in 3 seconds. Do you know any better idea?

**Comment by ffmmjj** [comment]
I know at least one person who recently used [this library](https://github.com/ageitgey/face_recognition) to do something like that to a reasonable enough accuracy. I strongly suggest to give it a try for this use case.

**Comment by adnan6336** [comment]
Ok sure I will. Thanks, really appreciated your work. :)

**Comment by ffmmjj** [comment]
Cool, I'll close this issue then. Good luck with your work.
